name: Approval-Based Staging Deploy with Email Alerts

on:
  push:
    branches: [staging]

jobs:
  notify_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email - Approval Pending
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Deployment Approval Needed for Staging"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            A deployment to the staging environment is pending approval.
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            Please review and approve in GitHub Actions.

  deploy:
    runs-on: ubuntu-latest
    needs: notify_approval
    environment:
      name: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Staging Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          source: "./"
          target: "/var/www/staging-site"
          overwrite: true

      - name: Send Email - Deployment Complete
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Staging Deployment Successful"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            Deployment to staging completed successfully!
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
